### ISSUE TITLE
TypeError: Cannot read property 'playersInRoom' of undefined

### ISSUE THREAD

**Issue by PlainReality** [MoreOutput/RockMUD#62]
When I start up the server and get logged in, the server crashes and throws this error.

```
Missing error handler on `socket`.
TypeError: Cannot read property 'playersInRoom' of undefined
    at C:\Users\treyw\Documents\NodeProjects\RockMUD\src\character.js:109:14
    at Character.hashPassword (C:\Users\treyw\Documents\NodeProjects\RockMUD\src\character.js:81:9)
    at Socket.<anonymous> (C:\Users\treyw\Documents\NodeProjects\RockMUD\src\character.js:100:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onevent (C:\Users\treyw\Documents\NodeProjects\RockMUD\node_modules\socket.io\lib\socket.js:335:8)
    at Socket.onpacket (C:\Users\treyw\Documents\NodeProjects\RockMUD\node_modules\socket.io\lib\socket.js:295:12)
    at Client.ondecoded (C:\Users\treyw\Documents\NodeProjects\RockMUD\node_modules\socket.io\lib\client.js:193:14)
    at Decoder.Emitter.emit (C:\Users\treyw\Documents\NodeProjects\RockMUD\node_modules\socket.io\node_modules\socket.io-parser\node_modules\component-emitter\index.js:134:20)
    at Decoder.add (C:\Users\treyw\Documents\NodeProjects\RockMUD\node_modules\socket.io\node_modules\socket.io-parser\index.js:247:12)
C:\Users\treyw\Documents\NodeProjects\RockMUD\server.js:175
                                for (j; j < roomObj.playersInRoom.length; j += 1) {
                                                   ^

TypeError: Cannot read property 'playersInRoom' of undefined
    at Socket.<anonymous> (C:\Users\treyw\Documents\NodeProjects\RockMUD\server.js:175:24)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.emit (C:\Users\treyw\Documents\NodeProjects\RockMUD\node_modules\socket.io\lib\socket.js:128:10)
    at Socket.onclose (C:\Users\treyw\Documents\NodeProjects\RockMUD\node_modules\socket.io\lib\socket.js:425:8)
    at Client.onclose (C:\Users\treyw\Documents\NodeProjects\RockMUD\node_modules\socket.io\lib\client.js:232:24)
    at Client.onerror (C:\Users\treyw\Documents\NodeProjects\RockMUD\node_modules\socket.io\lib\client.js:213:8)
    at Client.ondata (C:\Users\treyw\Documents\NodeProjects\RockMUD\node_modules\socket.io\lib\client.js:177:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

**Comment by MoreOutput** [comment]
Should've be fixed in tonights push.

**Comment by JayFett** [comment]
Should be noted that any characters created while this bug existed will have corrupt data (IE: roomid as a string) and will still crash the server if logged in to.
